# Generated by Django 4.1.3 on 2022-11-30 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=256)),
                ('img_path', models.CharField(blank=True, max_length=256, null=True)),
                ('ver_code', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('commodity_id', models.AutoField(primary_key=True, serialize=False)),
                ('commodity_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_contact', models.CharField(max_length=100)),
                ('note', models.CharField(default='请添加描述', max_length=120)),
                ('due_date', models.DateTimeField(auto_now_add=True)),
                ('picture', models.CharField(max_length=256)),
                ('user_id', models.ForeignKey(max_length=15, on_delete=django.db.models.deletion.CASCADE, related_name='user_id_Goods', to='secondhand_book.userinfo', unique=True)),
            ],
        ),
    ]
