# Generated by Django 4.1.3 on 2022-11-30 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secondhand_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='note',
            field=models.CharField(default='请添加描述', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='user_id',
            field=models.ForeignKey(max_length=15, on_delete=django.db.models.deletion.CASCADE, related_name='UserInfo_Goods', to='secondhand_book.userinfo', unique=True),
        ),
    ]
