# Generated by Django 4.1.3 on 2022-11-30 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secondhand_book', '0002_alter_goods_note_alter_goods_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='picture',
            field=models.CharField(default='D:/DjangoPro/transaction/secondhand_book/static/homepage/img/Math.webp', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='user_id',
            field=models.ForeignKey(max_length=15, on_delete=django.db.models.deletion.CASCADE, related_name='UserInfo_Goods', to='secondhand_book.userinfo'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='img_path',
            field=models.CharField(default='D:\\DjangoPro\\transaction\\secondhand_book\\static\\head\\user.webp', max_length=256, null=True),
        ),
    ]
