# Generated by Django 4.1.3 on 2022-11-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondhand_book', '0003_alter_goods_picture_alter_goods_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=256, unique=True),
        ),
    ]
