# Generated by Django 4.1.3 on 2022-12-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondhand_book', '0004_alter_userinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='user_id',
            field=models.CharField(max_length=15),
        ),
    ]
